apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: "Gitlab Actions"
inputs:
  url:
    description: 'gitlab url'
    required: false
    default: 'https://gitlab.com/'
  access-token:
    description: 'gitlab api  access token'
    required: true
  trigger-token:
    description: 'gitlab api trigger token'
    required: true
  namespace:
    description: 'namespace'
    required: true
  project-name:
    description: 'project name'
    required: true
  branch-name:
    description: 'branch name'
    required: true
  parameters:   
    description: 'parameters as json'
    required: false
    default: '{}'


runs:
  using: composite
  steps:
    - id: invoke-gitlab-action
      name: invoke-gitlab-action
      uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/gitlab-actions:main-c7ba948616e935967a2c9e91fcd253390d2f1c03
      shell: sh
      env: 
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{ step.internal.id }}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}
      run: |
        set -x
        cd /app
        ./gitlab_actions_app invoke -i '{"metaInfo":{"url":"${{ inputs.url }}","toolType":"GITLABACTIONS","accessToken":"${{ inputs.access-token }}","triggerToken":"${{ inputs.trigger-token }}","namespace":"${{ inputs.namespace }}","projectName":"${{ inputs.project-name }}","branchName":"${{ inputs.branch-name }}","parameters":${{ inputs.parameters }}}}'
